// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4iqWpfP9Fw3w68Bnb7gaRbEFKn47D5sE',
    appId: '1:1039045997366:web:76254f28cce26223937997',
    messagingSenderId: '1039045997366',
    projectId: 'pocketcheff-dspm2',
    authDomain: 'pocketcheff-dspm2.firebaseapp.com',
    storageBucket: 'pocketcheff-dspm2.appspot.com',
    measurementId: 'G-VLJB2PYJRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8IhNAhBVdgN9DQcuB5N5CybUiF8McNrs',
    appId: '1:1039045997366:android:d2193168805d3cda937997',
    messagingSenderId: '1039045997366',
    projectId: 'pocketcheff-dspm2',
    storageBucket: 'pocketcheff-dspm2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqNYHcDMpYCwPQUsvBIxKgXkSbhBd_sb4',
    appId: '1:1039045997366:ios:0ea0d93d62e6b8bf937997',
    messagingSenderId: '1039045997366',
    projectId: 'pocketcheff-dspm2',
    storageBucket: 'pocketcheff-dspm2.appspot.com',
    iosClientId: '1039045997366-vcas660khaj7oq7pjs4bskrc2c1cd4ee.apps.googleusercontent.com',
    iosBundleId: 'com.example.pockectcheff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqNYHcDMpYCwPQUsvBIxKgXkSbhBd_sb4',
    appId: '1:1039045997366:ios:0ea0d93d62e6b8bf937997',
    messagingSenderId: '1039045997366',
    projectId: 'pocketcheff-dspm2',
    storageBucket: 'pocketcheff-dspm2.appspot.com',
    iosClientId: '1039045997366-vcas660khaj7oq7pjs4bskrc2c1cd4ee.apps.googleusercontent.com',
    iosBundleId: 'com.example.pockectcheff',
  );
}
