// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDctYbQT3RczwxarHGVUKx5_f8zwUlMhP8',
    appId: '1:571903209511:web:e3baa7f9ea0dc98b2e9e02',
    messagingSenderId: '571903209511',
    projectId: 'pocketcheff-dspm',
    authDomain: 'pocketcheff-dspm.firebaseapp.com',
    storageBucket: 'pocketcheff-dspm.appspot.com',
    measurementId: 'G-3J3WKJYQK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr-_PdtJOPiJkKE_iG9mQLDB4MSqGrPTI',
    appId: '1:571903209511:android:cbf00cb0d6fe9b8b2e9e02',
    messagingSenderId: '571903209511',
    projectId: 'pocketcheff-dspm',
    storageBucket: 'pocketcheff-dspm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoBWSiYt4lxOCbk8pE7kcQP8x0T-X4gos',
    appId: '1:571903209511:ios:1da5a5d388bc3b462e9e02',
    messagingSenderId: '571903209511',
    projectId: 'pocketcheff-dspm',
    storageBucket: 'pocketcheff-dspm.appspot.com',
    iosClientId: '571903209511-148mndrc2ct98gdlh1ulqrp4tn5giu5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.pockectcheff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoBWSiYt4lxOCbk8pE7kcQP8x0T-X4gos',
    appId: '1:571903209511:ios:1da5a5d388bc3b462e9e02',
    messagingSenderId: '571903209511',
    projectId: 'pocketcheff-dspm',
    storageBucket: 'pocketcheff-dspm.appspot.com',
    iosClientId: '571903209511-148mndrc2ct98gdlh1ulqrp4tn5giu5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.pockectcheff',
  );
}
